
export const REACT_APP_AGENTIC_API_STATUS = process.env.REACT_APP_AGENTIC_API_STATUS



export const REACT_APP_SEARCH_API_BASE =  process.env.REACT_APP_SEARCH_API_BASE

export const REACT_APP_SEARCH_API_BASE_STATUS =  process.env.REACT_APP_SEARCH_API_BASE_STATUS

export const REACT_APP_AGENTIC_API_BASE = process.env.REACT_APP_AGENTIC_API_BASE


